name: Terraform CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    uses: AdamTurczynski/cicd-workflows/.github/workflows/terraform-reusable.yml@main
    with:
      terraform_dir: "."
      terraform_version: "1.9.8"
      aws_region: "eu-central-1"
      working_branch: "main"   
    secrets: inherit             